### ISSUE TITLE
dynamic invoice type

### ISSUE THREAD

**Issue by ldumlija** [dingo-d/woo-solo-api#76]
Pozdrav,

koristim Vas plugin na jednoj instalaciji pa me zanima postoji li neki filter/nacin da dinamicki posaljem tip racuna.

Naime na checkout stranici imam custom dropdown za odabir tipa subjekta (privatna osoba | tvrtka | javna ustanova) i ovisno o tome se prikazuju input fieldovi za OIB/naziv/ime/prezime itd. Ovisno o tom odabiru ja bi volio imati mogucnost poslati tip R racuna za privatnu i R1 za ostale tipove.

Koliko sam ja ovako uspio vidjeti trenutno se gleda iskljucivo option u postavkama SOLO plugina, ali mozda sam nesto previdio.

Hvala unaprijed!

**Comment by dingo-d** [comment]
Pozdrav,

Nemam filtere za modifikaciju request podataka, ali ovo je dost dobra sugestija. Dodat cu je na popis pa cu probat dodati u iduci update 🙂

**Comment by ldumlija** [comment]
kao workaround sam napravio dinamicki update optiona, tako da zapravo prije nego se pozove plugin azuriram option plugina (tip racuna) i nakon toga dalje sve radi kako mi odgovara.

**Comment by dingo-d** [comment]
Pozdrav!

U verziji 3 sam dodao nove filtere koji bi mogli pomoc:

### Modify the bill type

Use this filter if you need to dynamically change the bill type.

Usage:

```php
add_filter('woo_solo_api_modify_bill_type', 'my_customer_filter', 10, 3);

function my_customer_filter($billType, $paymentMethod, $order) {
  // (maybe) modify $billType, based on some external parameters or $paymentMethod or $order.
  return $billType;
}
```

```
@param string $billType Existing bill type.
@param string $paymentMethod Selected payment method for the current order.
@param object|WC_Order $order Current order.
```

### Filter the unit measure for the current item

Use this filter if you need to dynamically change measure for the item.
Unit measure *MUST* be an integer in the list of measures (check the API documentation for details).

```php
add_filter('woo_solo_api_modify_item_measure', 'my_customer_filter', 10, 4);

function my_customer_filter($measure, $itemNo, $order, $itemData) {
  // Modify multiple item numbers in your order based on some settings, meta value, etc.
  switch ($itemNo) {
    case 0:
      $measure = 7;
      break;
    case 1:
      $measure = 19;
      break;
    default:
      $measure = 2;
      break;
  }

  // Or filter based on $order object or $itemData which contains other information about the product.

  return $measure;
}
```

```
@param int $measure Current unit measure.
@param int $itemNo Current item in the list.
@param object|WC_Order $order Current order.
@param array $itemData Current item data.
```

### Filter the unit measure for the current shipping item

Use this filter if you need to dynamically change measure for the shipping item.
Unit measure *MUST* be an integer corresponding to the list of measures.

Be careful when changing the measure using the above filter, as the shipping item should probably be a `piece (2)`.

```php
add_filter('woo_solo_api_modify_shipping_item_measure', 'my_customer_filter', 10, 4);

function my_customer_filter($measure, $itemNo, $order, $itemData) {
    return 2; // Corresponds to: piece.
}
```

```
@param int $measure Current shipping unit measure. Will be picked up by whatever is in the default measure.
@param int $itemNo Current item in the list.
@param object|WC_Order $order Current order.
@param object|null $shippingObject Current shipping item data.
```

Nadam se da ce ovo pomoc.
