### ISSUE TITLE
Payment option should not be global

### ISSUE THREAD

**Issue by ivoks** [dingo-d/woo-solo-api#9]
Currently one can select a payment option (Cash, Card, Check...) and this is applied globally. So, if someone has different payment gateways in woocommerce, they all need to be the same.

A use case would be a web page that allows payment via Credit card, but also via bank transaction. Now, even a bank transaction option results in an invoice that is marked as credit card payment.

IMHO, one should be able to select 'fiscal option', 'type of the document' and 'payment option' for every gateway. As an example:

- PayPal - fiscalized, invoice, credit card
- WSpay - fiscalized, invoice, credit card
- bank transfer - not fiscalized, offer, bank transaction

**Comment by dingo-d** [comment]
You mean add the payment type in the 'Choose the type of payment for each enabled payment gateway' option? Never thought of it tbh, but makes sense. I'll change this

**Comment by dingo-d** [comment]
Fixed in the latest version (1.7). I'll tag it and release. Thanks for pointing this out :)

**Comment by ivoks** [comment]
Thank you!
